services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:dev
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app/config:rw
      - ./images:/app/public/images
      - /etc/localtime:/etc/localtime:ro
    networks:
      - docker
    environment:
      - TZ=
      - DOCKER_HOST=
      - LOG_LEVEL=debug
    env_file:
      - .env
