services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - TZ=Asia/Singapore
      - DOCKER_HOST=tcp://192.168.1.88:2375
      - LOG_LEVEL=debug
      - HOMEPAGE_ALLOWED_HOSTS=homepage.abdulmuizz.dev,192.168.1.69:3333,192.168.1.88:3333
    env_file:
      - .env
    volumes:
      - ./config:/app/config:rw  # Separated from compose directory
      - ./images:/app/public/images
      - /mnt/data:/data:ro  # Read-only access to data
      - /mnt/usb:/usb:ro   # Read-only access to USB
      - /mnt/docker:/docker:ro  # Read-only access to docker data
    ports:
      - "3333:3000"
    restart: unless-stopped
    networks:
      - komodo
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Memory limits only (no CPU limits for cgroup compatibility)
    mem_limit: 512m  # Reduced from 4g - Homepage is lightweight
    memswap_limit: 2g
    # cpus: "0.25"
    security_opt:
      - no-new-privileges:true
    # Log management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  komodo:
    external: true
